coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 0%
        base: auto
        only_pulls: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
