/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration for initializing the CaptchaApi */
export interface CaptchaConfig {
  /** SQLite database URL (e.g., "sqlite:./captcha.db") */
  databaseUrl: string
  /** Salt used for hashing API keys */
  apiKeySalt: string
  /**
   * Server-side key used to hash CAPTCHA solutions before storing them.
   * Defaults to `apiKeySalt`. Keep it out of the database — a stolen
   * database is useless without it.
   */
  solutionHashSecret?: string
  /** Default session TTL in seconds (default: 300) */
  defaultSessionTtlSeconds?: number
  /** Maximum allowed session TTL in seconds (default: 3600) */
  maxSessionTtlSeconds?: number
  /** Maximum validation attempts per session (default: 3) */
  maxValidationAttempts?: number
  /** Run database migrations on startup (default: true) */
  runMigrations?: boolean
  /** Default JPEG compression quality 1-100 (default: 40) */
  captchaCompression?: number
}
/** Options for creating a new CAPTCHA session */
export interface CreateSessionOptions {
  /** CAPTCHA text length 1-20 characters (default: 5) */
  length?: number
  /** Session expiration in seconds (uses default if not provided) */
  expiresInSeconds?: number
  /** Difficulty level from 1-10 (default: 5) */
  difficulty?: number
  /** Image width in pixels (default: 220) */
  width?: number
  /** Image height in pixels (default: 120) */
  height?: number
  /** Use dark mode colors (default: false) */
  darkMode?: boolean
  /** JPEG compression quality 1-100 (default: 40) */
  compression?: number
}
/** Result of creating a CAPTCHA session */
export interface SessionResult {
  /** Unique session identifier (UUID) */
  sessionId: string
  /**
   * The generated CAPTCHA text (solution).
   * Available in the library API for server-side use.
   * Note: The HTTP REST API does NOT expose this field to clients.
   */
  text: string
  /** Session creation timestamp (Unix milliseconds) */
  createdAt: number
  /** Session expiration timestamp (Unix milliseconds) */
  expiresAt: number
  /** CAPTCHA image as JPEG bytes */
  image: Buffer
}
/** Session information (without the image) */
export interface SessionInfo {
  /** Unique session identifier (UUID) */
  sessionId: string
  /** Session creation timestamp (Unix milliseconds) */
  createdAt: number
  /** Session expiration timestamp (Unix milliseconds) */
  expiresAt: number
  /** Number of validation attempts made */
  attemptCount: number
  /** Difficulty level (1-10) */
  difficulty: number
  /** Image width in pixels */
  width: number
  /** Image height in pixels */
  height: number
  /** Whether dark mode is enabled */
  darkMode: boolean
}
/** Result of validating a CAPTCHA solution */
export interface ValidationResult {
  /** Whether the solution was correct */
  valid: boolean
  /** Session ID that was validated */
  sessionId: string
  /** Number of attempts remaining (0 if exhausted or valid) */
  attemptsRemaining: number
}
/** Information about an API key */
export interface ApiKeyInfo {
  /** SHA256 hash of the API key */
  keyHash: string
  /** Optional description of the key */
  description?: string
  /** Creation timestamp (Unix milliseconds) */
  createdAt: number
  /** Last usage timestamp (Unix milliseconds), if ever used */
  lastUsedAt?: number
  /** Whether the key is active */
  isActive: boolean
}
/** Result of creating a new API key */
export interface CreateApiKeyResult {
  /** The raw API key (only returned once, store it safely!) */
  apiKey: string
  /** The hash of the API key (for reference) */
  keyHash: string
}
/** Options for generating a CAPTCHA without storing it */
export interface GenerateOptions {
  /** CAPTCHA text length 1-20 characters (default: 5) */
  length?: number
  /** Difficulty level from 1-10 (default: 5) */
  difficulty?: number
  /** Image width in pixels (default: 220) */
  width?: number
  /** Image height in pixels (default: 120) */
  height?: number
  /** Use dark mode colors (default: false) */
  darkMode?: boolean
  /** JPEG compression quality 1-100 (default: 40) */
  compression?: number
}
/** Result of generating a CAPTCHA (stateless, not stored) */
export interface GenerateResult {
  /** The CAPTCHA solution text */
  solution: string
  /** CAPTCHA image as JPEG bytes */
  image: Buffer
}
/**
 * Main CAPTCHA API client for Node.js
 *
 * This class provides all CAPTCHA operations including session management,
 * validation, and API key management.
 *
 * @example
 * ```typescript
 * const api = await CaptchaApi.create({
 *   databaseUrl: 'sqlite:./captcha.db',
 *   apiKeySalt: 'your-secret-salt'
 * });
 *
 * const session = await api.createSession({ difficulty: 5 });
 * const isValid = await api.validate(session.sessionId, userAnswer);
 * ```
 */
export declare class CaptchaApi {
  /**
   * Create a new CaptchaApi instance
   *
   * This is an async factory method that initializes the database connection
   * and runs migrations if configured.
   *
   * @param config - Configuration options for the API
   * @returns A promise that resolves to a CaptchaApi instance
   */
  static create(config: CaptchaConfig): Promise<CaptchaApi>
  /**
   * Create a new CAPTCHA session
   *
   * Generates a CAPTCHA image and stores the session in the database.
   * The session will expire after the configured TTL.
   *
   * @param options - Optional settings for the CAPTCHA
   * @returns Session information including the image
   */
  createSession(options?: CreateSessionOptions | undefined | null): Promise<SessionResult>
  /**
   * Validate a CAPTCHA solution
   *
   * Checks if the provided solution matches the session's expected answer.
   * The session is deleted on successful validation.
   * After max attempts, the session becomes invalid.
   *
   * @param sessionId - The session ID to validate
   * @param solution - The user's answer
   * @returns Validation result
   */
  validate(sessionId: string, solution: string): Promise<ValidationResult>
  /**
   * Get the CAPTCHA image for a session
   *
   * @param sessionId - The session ID
   * @returns The JPEG image as a Buffer
   */
  getImage(sessionId: string): Promise<Buffer>
  /**
   * Get session information (without the image)
   *
   * @param sessionId - The session ID
   * @returns Session metadata
   */
  getSession(sessionId: string): Promise<SessionInfo>
  /**
   * Delete a session
   *
   * @param sessionId - The session ID to delete
   * @returns True if the session was deleted, false if not found
   */
  deleteSession(sessionId: string): Promise<boolean>
  /**
   * Delete all expired sessions
   *
   * This is useful for cleanup. In the HTTP server, this runs automatically
   * in a background task.
   *
   * @returns Number of sessions deleted
   */
  cleanupExpired(): Promise<number>
  /**
   * Generate a CAPTCHA without storing it (stateless)
   *
   * This is useful for custom implementations where you want to manage
   * storage yourself.
   *
   * @param options - Optional settings for the CAPTCHA
   * @returns The solution and image
   */
  generate(options?: GenerateOptions | undefined | null): GenerateResult
  /**
   * Create a new API key
   *
   * @param description - Optional description for the key
   * @returns The API key (store it safely!) and its hash
   */
  createApiKey(description?: string | undefined | null): Promise<CreateApiKeyResult>
  /**
   * Validate an API key
   *
   * @param apiKey - The API key to validate
   * @returns True if the key is valid and active
   */
  validateApiKey(apiKey: string): Promise<boolean>
  /**
   * Get API key information by hash
   *
   * @param keyHash - The hash of the API key
   * @returns API key information if found
   */
  getApiKey(keyHash: string): Promise<ApiKeyInfo | null>
  /**
   * List all API keys
   *
   * @returns List of all API keys (hashes, not the actual keys)
   */
  listApiKeys(): Promise<Array<ApiKeyInfo>>
  /**
   * Update an API key
   *
   * @param keyHash - The hash of the API key to update
   * @param isActive - New active status (optional)
   * @param description - New description (optional)
   * @returns True if the key was updated
   */
  updateApiKey(keyHash: string, isActive?: boolean | undefined | null, description?: string | undefined | null): Promise<boolean>
  /**
   * Delete an API key
   *
   * @param keyHash - The hash of the API key to delete
   * @returns True if the key was deleted
   */
  deleteApiKey(keyHash: string): Promise<boolean>
  /**
   * Close the database connection
   *
   * Call this when you're done using the API to cleanly close connections.
   */
  close(): Promise<void>
}
